version: '3'
services:
  java-code-runner:
    image: java-code-runner
    volumes:
      - ./example:/app/execution
    container_name: java-example-container
    user: "${UID}:${GID}"
    environment:
      - test_count=2
      - time_limit=1
      - memory_limit=200000