version: '3'
services:
  java-code-runner:
    build:
      context: .
    volumes:
      - ./example:/app/execution
    container_name: java-example-container
    user: "${UID}:${GID}"
    environment:
      - test_count=2