spring:
  application:
    name: problems
  data:
    mongodb:
      database: problems-db
      host: localhost
      port: 9100
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

execution:
  service:
    url: http://localhost:8085