version: '3'
services:
  front:
    build:
      context: ../macscode-front
    ports:
      - "3000:3000"
  macscode-dummy-back:
    build:
      context: ../macscode
    ports:
      - "8080:8080"
  problems-db:
    image: mongo:latest
    ports:
      - 9100:27017
    volumes:
      - ./problemsdb:/data/db
