version: '3'
services:
  front:
    container_name: front-container
    build:
      context: ../macscode-ui
    ports:
      - "3000:3000"

  macscode-dummy-back:
    container_name: macscode-dummy
    build:
      context: ../macscode
    ports:
      - "8080:8080"
  problems-db:
    container_name: problems-db
    image: mongo:latest
    ports:
      - 9100:27017
    volumes:
      - ./problemsdb:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth-service:
    container_name: auth-service
    build:
      context: ../auth-service
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_started
    networks:
      - macscode_network
    env_file:
      - .env

  db:
    image: 'postgres:16.2'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - macscode_network
    env_file:
      - .env

volumes:
  pgdata:
  rabbitmq_data:
networks:
  macscode_network: