version: '3'
services:
  front:
    container_name: front-container
    build:
      context: ../macscode-ui
    ports:
      - "3000:3000"
    networks:
      - macscode_network
    env_file:
      - .env
  problems-db:
    container_name: problems-db
    image: mongo:latest
    ports:
      - 9100:27017
    volumes:
      - ./problemsdb:/data/db
    networks:
      - macscode_network
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - macscode_network
    env_file:
      - .env
  auth-service:
    container_name: auth-service
    build:
      context: ../auth-service
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_started
    networks:
      - macscode_network
    env_file:
      - .env
  problems-service:
    container_name: problems-service
    build:
      context: ../problems
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_started
      problems-db:
        condition: service_started
    networks:
      - macscode_network
    env_file:
      - .env
  executor-service:
    container_name: executor-service
    build:
      context: ../executor
    depends_on:
      problems-service:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    privileged: true
    networks:
      - macscode_network
    env_file:
      - .env
  discussion-service:
    container_name: discussion-service
    build:
      context: ../discussion-service
    ports:
      - "8082:8082"
    depends_on:
      problems-db:
        condition: service_started
    networks:
      - macscode_network
    env_file:
      - .env
  db:
    image: 'postgres:16.2'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - macscode_network
    env_file:
      - .env
volumes:
  pgdata:
  rabbitmq_data:
networks:
  macscode_network: