version: '3'
services:
  front:
    build:
      context: ../macscode-front
    ports:
      - "3000:3000"
  macscode-dummy-back:
    build:
      context: ../macscode
    ports:
      - "8080:8080"
  auth-service:
    build:
      context: ../auth-service
    ports:
      - "8081:8081"
  db:
    image: 'postgres:15.3-alpine'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_dmtp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
volumes:
  pgdata: