version: '3'
services:
  front:
    build:
      context: ../macscode-front
    ports:
      - "3000:3000"
  macscode-dummy-back:
    build:
      context: ../macscode
    ports:
      - "8080:8080"
  auth-service:
    build:
      context: ../auth-service
    ports:
      - "8081:8081"