spring:
  boot:
    admin:
      client:
        url: http://localhost:8087
  application:
    name: executor
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always